### ISSUE TITLE
Warning under Visual Studio 2015

### ISSUE THREAD

**Issue by LiorKogan** [Cyan4973/xxHash#36] opened 2015-11-18 13:59 UTC
The code generates the following warning messages under VS2015:

xxhash.cpp(565): warning C4804: '/': unsafe use of type 'bool' in operation
xxhash.cpp(576): warning C4804: '/': unsafe use of type 'bool' in operation

These warnings refer to the following line:

#define XXH_STATIC_ASSERT(c)   { enum { XXH_static_assert = 1/(!!(c)) }; }    /* use only *after* variable declarations */

**Comment by Cyan4973** [comment] 2015-11-18 14:07
mmmh, it seems to defeat the point.
This is a static test, designed specifically to control the size of context structures.
Error is triggered in case the context size is increased without a corresponding increase in its opaque container. That being said, it's not really useful as long as nothing changes.

The entire point is to create a compilation error in case of source code change. If VS2015 considers this construction a "warning", it defeats the intention.

2 possible solutions : 
1) disable this warning from within the `xxhash.c` source code : 
`#  pragma warning(disable : 4804)    /* disable: C4804: division by bool */`
2) disable the static assert

**Comment by LiorKogan** [comment] 2015-11-18 14:15
Adding a cast solves it as well:

#define XXH_STATIC_ASSERT(c)   { enum { XXH_static_assert = 1/(int)(!!(c))
}; }    /* use only *after* variable declarations */

**Comment by Cyan4973** [comment] 2015-11-18 14:18
If that's all it takes ... :+1:

Thanks ! I'll add this patch in the next source update

**Comment by Cyan4973** [comment] 2016-01-04 05:02
It took me quite a while to be able to reproduce this issue.
I went to great length to install Visual 2015 on my overcrowded dev station, only to discover the issue is not specific to 2015.

In fact, the only way to trigger this warning is to compile `xxhash.c` _as a C++ file_ `/TP`.

Once that's done, it's possible to trigger the warning and verify the fix is effective.

This fix will be part of next release.

**Closed by Cyan4973** 2016-01-04 05:02 UTC

**Comment by t-mat** [comment] 2016-01-04 05:36
Since `!!(c)`'s type conversions are [different](https://en.wikipedia.org/wiki/Boolean_data_type#C.2C_C.2B.2B.2C_Objective-C.2C_AWK),

 - anytype -> `int` in C89
 - anytype -> `_Bool` in C99/11, but `_Bool` is compatible with `int`.
 - anytype -> `bool` in C++, `bool` is incompatible with `int`.

perhaps using explicit integer expression `((c) ? 1 : 0)` or `((c) != 0 ? 1 : 0)` would be better than `(!!(c))`for this purpose.

**Comment by Cyan4973** [comment] 2016-01-04 05:38
Thanks for insightful clarifications @t-mat.

> perhaps using explicit integer expression

good point !

**Comment by petervaro** [comment] 2016-01-05 00:28
@Cyan4973 wouldn't it be better, to use a *real* static assertion if available? I mean something like this:

```C
/* If ISO C11 or higher */
#if __STDC_VERSION__ >= 201112L
    #include <assert.h>
    #define XXH_STATIC_ASSERT(c) static_assert(c, "<your message goes here>")
/* If ISO C++11 or higher */
#elif __cplusplus >= 201103L
    #define XXH_STATIC_ASSERT(c) static_assert(c, "<your message goes here>")
/* Anything else */
#else
    // define the way you already did
#endif
```

*(Warning: though I did not tested the above snippet, I'm pretty sure it will work)*

**Comment by Cyan4973** [comment] 2016-01-05 00:36
Yes @petervaro, you are right,
the main issue is that C11 is not yet very common, with the majority of deployed systems still expecting C99 if not C90.

Using _C11 static assert_ do not give us a lot of value, considering it's still necessary to preserve current method for all other compilers. The only benefit I can see is a clearer warning message.

Obviously, with evolution of compiler ecosystem, the benefit of using C11-only keywords will become more enticing.
