### ISSUE TITLE
[humble request] add support for input from flash memory (memcpy_P)

### ISSUE THREAD

**Issue by atesin** [Cyan4973/xxHash#745] opened 2022-10-13 22:44 UTC
hi... as all we know, hhXash is a very small and efficient hash algoritm, what makes it perfect for embedded systems

most embedded systems with harvard architecture (like development boards, home routers, soc's, thin clients, media centers, etc.) have eeprom/flash memory storages and have the capability to read data directly from program flash memory to save ram

recently i had a problem trying to make streaming mode work in arduino uno (stripped down example)
```
XXH32_state_t *state = XXH32_createState();
XXH32_reset(state, 0);
XXH32_update(state, "ardu", 4);
XXH32_update(state, (PGM_P) F("ino"), 3);
```
**the program crashes** at 4th line because it doesn't know what to do with `(PGM_P) F("ino")` what is a pointer to a char array (c_str) stored in higher program flash memory

for these situations where data resides in program memory, avr, xtensa, gnu c++ compilers and many other architectures and sdk's have the `*_P` version for some functions, like `strlen_P()`, `strcpy_P()`, `memcpy_P()`, etc. (i.e. [for arduino](https://www.nongnu.org/avr-libc/user-manual/group__avr__pgmspace.html#func-members), [for esp8266](https://arduino-esp8266.readthedocs.io/en/3.0.2/PROGMEM.html#functions-to-read-back-from-progmem))

i tried adding this function to `xxhash.h` in line ~1740 and add support for `XXH32_update()` as a test for my particular case and worked flawlessly...
```
static void* XXH_memcpy_P(void* dest, const void* src, size_t size)
{
    return memcpy_P(dest,src,size);
}
```
if you think it could help small systems users and worth to be added later, more `*_P` functions could be "oficially" added and enabled/disabled through a [build modifier](https://github.com/Cyan4973/xxHash#build-modifiers)

please tell us what do you think, and if you think it could be a good idea

**Comment by t-mat** [comment] 2022-10-13 23:59
Good point.
We may be able to split the change with the following changes and additinal issues.

### (1) Eliminate raw `memcpy()` from xxhash.h

Unfortunately, we have some raw `memcpy()` in xxhash.h which can be found with the following command

```
$ grep -n "[^_]memcpy" ./xxhash.h
```

We should eliminate them before other changes.


### (2) Introduce new build modifier macro `XXH_MEMCPY`

Define the following macro somewhere in xxhash.h

```
#if !defined(XXH_MEMCPY)
#  define XXH_MEMCPY XXH_memcpy
#endif
```

And use `XXH_MEMCPY` everywhere instead of `XXH_memcpy`


### (3) note: We should avoid to use `XXH_MEMCPY` outside of xxhash.h

Since tests and CLI are depend on "standard" stdlib,
I think we should not use `XXH_MEMCPY` outside of xxhash.h.


### (4) problem: How can we test and keep these changes?

Since `memcpy()` works fine in almost all platforms, I have no idea so far.

- Setting explicit memory protection (set source memory region as "write-only" memory)?
- Define special `memcpy()` which detect unintended memory access?

**Comment by Cyan4973** [comment] 2022-10-14 00:07
If I understand correctly,
it seems that @atesin wants to circumvent a limitation of `memcpy()`,
which makes it unable to read from pointers of the kind `(PGM_P)`.

I'm indeed surprised to learn that `memcpy()` has such limitation.
I would have expected it to be able to read from read-only ROMs for example,
hence from higher program flash memory too.

Anyway, assuming this is not classified as a `memcpy()` bug,
and that the acknowledged solution is to invoke a variant `memcpy_P()` instead,
then yes, one could imagine a way to allow a compile-time redirection of `memcpy()` for xxhash.

Indeed, the first step, as mentioned by @t-mat, should be to ensure that there is no direct call to `memcpy()`,
and everything is invoked through `XXH_mempcy()`,
so that the modification only needs to be done in one place.

**Comment by t-mat** [comment] 2022-10-14 00:23
### potential issue: How can we mix `memcpy` (RAM to RAM) and `memcpy_P`(PROGMEM to RAM) ?

Both of AVR and Tensilica have families/variants which contains/supports larger RAM.
So some apllication or variant processor user may want to use `memcpy` (RAM to RAM) instead of `memcpy_P` (PROGMEM to RAM).

Possible solutions are

- Leave it as is.  I think it's okay to trust application developers who can choose proper compile options.
- They must define their own unique `XXH_NAMESPACE`s for `memcpy` and `memcpy_P` variant.
- (C++) Surround `#include "xxhash.h"` with `namespace {}`.
- (C++/extreme) Use `#embed` and `constexpr` for read-only/AOT-immutable data. 😈

**Comment by Cyan4973** [comment] 2022-10-14 00:32
oh, so `memcpy_p()` (or `memcp_P()`?) is not a superset of `memcpy()`, and must be used carefully for the right circumstances ?
I presume the differentiation comes from the `src` pointer, which is `const void*` for the "normal" case, but has a different type for these specific scenarios ?

In which case, I could imagine a C11 macro solution based on `_Generic`, 
but indeed, the exact implementation would have to be done specifically for each project. 

One important thing xxhash can provide is to ensure that all `memcpy()` operations are controlled through `XXH_memcpy()`. But I suspect it won't be enough. Functions like `XXH32_update()` would likely need a similar treatment, and now it becomes specific enough to be dealt with in a dedicated fork.

**Comment by t-mat** [comment] 2022-10-14 01:03
AFAIK, AVR has dedicated instruction for each memory type.

- Program memory : `lpm` (Load Program Memory) or its variant.
- Normal memory : `lds` (Load direct from Data Space) or its variant.

And actual implementation of `memcpy_P()` explicitly uses `lpm` (`X_lpm` in the code).

http://svn.savannah.nongnu.org/viewvc/avr-libc/trunk/avr-libc/libc/pmstring/memcpy_P.S?view=markup

> oh, so memcpy_p() (or memcp_P()?) is not a superset of memcpy(), and must be used carefully for the right circumstances ?

( Sorry, I mean `memcpy_P()`.  I edited my previous post. )

Yes, application programmer must carefully recognize their situation and choose `memcpy()` or `memcpy_P()`.

> I presume the differentiation comes from the src pointer, which is const void* for the "normal" case, but has a different type for these specific scenarios ?

I'm not sure about ability of recent compilers.
But since their instructions are completely different, they likely should use proper functions/instructions for them manually.

> One important thing xxhash can provide is to ensure that all memcpy() operations are controlled through XXH_memcpy(). But I suspect it won't be enough. Functions like XXH32_update() would likely need a similar treatment, and now it becomes specific enough to be dealt with in a dedicated fork.

Right. If we'll support these NUMA platform, I think we should define and use the following functions
- Copy source (special, readonly memory) to main RAM (or register).
- Copy main RAM memory to main RAM.

And I'm not sure we still have speed gain with these restrictions or not.

**Comment by atesin** [comment] 2022-10-14 04:26
hi... thanks for your interest

@t-mat 
> ### (2) Introduce new build modifier macro `XXH_MEMCPY`
> Define the following macro somewhere in xxhash.h

i suggest another name like **XXH_PROGMEM** more appropiate for this case, since the latter sounds specific to that function and not generic for all possibly progmem functions needed

also, i think support for progmem functions should be **added**, not switched or replaced... see for example the first example i posted in which we can see calls to overloaded `XXH32_update()` with both datatypes `char *` and `PGM_P`

be aware in this case `PGM_P` is just a macro replacement for `char *` so it doesn't work for typecasting... for a deeper explanation read [THIS](https://arduino-esp8266.readthedocs.io/en/3.0.2/PROGMEM.html) (this is for esp8266 but works mostly similar for arduino, be aware `FPSTR` macro is not present in arduino)

@Cyan4973 
i guess the components/circuitry/process/timings/addresses/etc to read eeprom/flash memory are different from normal ram operations, so they deserve different opcodes/functions ... as i noted above, `PGM_P` doesn't work for typecasting, that is why my program **did compile**, but crashed at runtime... for same reason you can't rely easily on overloaded `PGM_P` functions (read the explanation linked above)... in this case, chances are users (i.e. app developers) **know** when they are working with progmem data, so writing `*_P` functions like `XXH32_P()` or `XXH32_update_P()` won't hurt them...

i believe `*_P` functions are not part of ansi c standard, but part of some gnu c++ compilers... remember available `*_P` functions internally use specific opcodes to work directly with flash memory through different platforms, so we can just go and use them for ease

even until i know is not optimal (especially for such a limited platform like arduino and similar), in the meanwhile i am trying the workaround below  ... so i think the point all this conversation is to actually to keep the work with this lib blaze optimized and avoid heavy workarounds like this snippet:
```
// having a previously instantiated and resetted hash state, and another feed(char*) function
void feed(const __FlashStringHelper *inputData){
  if ( !errorCode ){
    // for code below i'm wating what happen with: https://github.com/Cyan4973/xxHash/issues/745
    //errorCode = XXH32_update_P(state, (PGM_P) inputData, strlen_P((PGM_P) inputData));
    // slimy workaround in the meanwhile...
    char bufData[17];  // yes, another temporary buffer :/
    bufData[16] = '\0';  // strncpy_P() below doesn't terminate strings
    PGM_P ptrData = (PGM_P) inputData;
    PGM_P endData = ptrData + strlen_P(ptrData);
    while ( ptrData < endData ){  // yes another iteration :/
      strncpy_P(bufData, ptrData, 16);
      feed(bufData);
      ptrData += 16;
    }
  }
}
```

**Comment by Cyan4973** [comment] 2023-07-15 17:35
Closing. It seems a version differentiating `memcpy()` from `memcpy_P()` depending on memory type is out of scope for this repository, as it would significantly impact the entire code base for the benefit of a single specific use case.

**Comment by atesin** [comment] 2023-07-15 18:29
hi... i know this issue is closed .. don't be so drastic yet, because the solution may be more simple than you think

since it had been some time from this issue, maybe i forgot some details (additionally, i am not a C/C++ programmer but a regular user, so to have been able to talk in same tech level with you fills me with pride :) )

... but basically, taking the example from my opening post and the commonn existence of `PROGMEM` macro discussed here, i think simply a code like this could be added

```
#ifdef PROGMEM
static void* XXH_memcpy_P(void* dest, const void* src, size_t size)
{
    return memcpy_P(dest,src,size);
}
#endif
```

this should make available the new `XXH_memcpy_P()` function **only if** the platform supports progmem functions (assuming a platform with no progmem functions have no `PROGMEM` macro defined ;) (at least avr and xtensa, maybe stm32 and others))

whaf if you reopen the issue and request it to some skilled collaborator? (i could make a blind PR if you want)

thanks

**Comment by Cyan4973** [comment] 2023-07-15 19:22
I think the issue here is that we must first make a complete pass over the code to understand where the `memcpy()` function is invoked, both directly and indirectly,
in order to ensure that _only_ the parts that read from `input` get impacted by the `memcpy_P()` change, while all other parts continue to use the regular `memcpy()`.

I suspect this is a bit more complex to ensure than it sounds, but it would still be tractable if limited to `XXH32`, and likely `XXH64`. It tends to become more complex though with `XXH3_*` variants. And the issue is, all these variants share the same read functions kernel.

**Comment by Cyan4973** [comment] 2024-12-09 08:08
Note: this request will likely become easier to handle once the library is cut into multiple smaller parts.

**Comment by atesin** [comment] 2024-12-11 02:57
maybe the fix is more easy than we thought ...  taking the example in my first post, maybe it should be enough just to add macro guards like:
```
#ifdef PGM_P
static void* XXH_memcpy_P(void* dest, PGM_P src, size_t size)
{
    return memcpy_P(dest, src, size);
}
#endif
```
at least i am sure it will work in arduino, esp8266-arduino, esp32-arduino and maybe other arduino based projects ...  anyway it seem that `*_P` functions are like a de-facto standard for harvard architectures that have separate instructions to read static ram and nand/nor flash, that i guess they work different in hardware

**Comment by Cyan4973** [comment] 2024-12-27 07:14
Quick question about the use case:

if I understand correctly, accessing "regular" memory, using for example `memcpy()`,
is radically different from accessing the flash or read-only memory with `memcpy_P()`.

And to be fair, this is expected. In a "regular" posix system, one doesn't access block devices like RAM.

Which leads to this natural follow-up: why not just copy data from the flash memory into regular memory (using `memcpy_P()`), by segment of any size depending on the embedded system capacity, and then push the copied segment into `xxh` using a streaming variant like `XXHxx_update()` ?

**Comment by atesin** [comment] 2024-12-27 17:09
> why not just copy data from the flash memory into regular memory (using `memcpy_P()`)

"_or why not for who needs, just to download code and modify locally by him/her self?_"... as i did?

surely blocks of data can be copied from flash to sram with `memcpy_P()` and then process regularly with `XXH*` functions, this request is just to provide an aid to microcontroller programmers (think there are a lot of beginners in arduino for example, including teachers and students, and even elderly gentlemen/ladies)... so i quickly see at least 2 reasons why this could be useful:

- to save some extra steps by avoid copying blocks of data between flash and sram, the more large the the block the more cpu cycles needed because they are copied iteratively by byte since mcu lacks SIMD instructions... and even more because flash operations are times slower than sram ops
- system limitations: for example arduino uno have 2kb of sram and about 30kb of flash, this leave about 1/2 kb of free sram at runtime, so usually constant text blocks are stored in flash, for sketches that process "large" texts with a copule hundreds of bytes (like http, or a mud/rpg game, a chatbox, etc) maybe they wont fit in sram to be processed so it has to be processed directly in flash

i am not an expert in hardware designs, but although in some platforms like arduino uno, the cpu address bus is 15-bit wide (0 - 32767) they are mapped so address 0-512 points to eeprom, the next 2kb block points to sram and the rest of ~30kb to flash, so the cpu (atmega 328p) can point to different hardware circuitry depending the address although is in the same 15-bit range

they are way different, sram are built on capacitors that are refreshing each cycle to avoid discharge, nvram are non volatile ram that has a battery to avoid discharge, prom are uv-light programable (erasable) rom, eeprom are electrically erasable prom, flash are made with induction coils or transistors or logic gates that traps a charge or whatever.... so although they fit in the same 32kb address space there are segments that work different, for instance eeprom/flash reads are slower (i.e. more cycles) and cannot be written at runtime

for more detailed info take a look into [harvard architecture](https://en.wikipedia.org/wiki/Harvard_architecture) often used in microcontrollers where blocks of memory points to different circuits, and [von neumann architecture](https://en.wikipedia.org/wiki/Von_Neumann_architecture) often used in computers where all address space is the same type of RAM

**Comment by Cyan4973** [comment] 2024-12-27 18:36
Determining the appropriate scope for each software layer can be challenging. There is often a tendency toward “feature creep,” driven by the misconception that code creation is the primary expense. In practice, long-term maintenance is the larger cost, increasing complexity adds risk, slower development, and in turn lead to developer fatigue.

For this reason, any new feature should yield a clear benefit relative to its cost. In this case, the benefit is a potentially simpler workflow for implementing `xxh32` on embedded systems. Moreover, a practical approach could be to build a small wrapper around `libxxhash`—copying data from flash to memory in small chunks (e.g., 16 bytes)—or to offer this functionality as a standalone library for embedded systems. Given the niche nature of the use case, it would be appropriate.

While it’s technically possible to integrate the same layer directly into the upstream library, the key question is whether that’s the right choice. Adding specialized behavior can burden all users, including those who do not need it, by causing confusion, information overload, and maintenance creep. It also slows down future development.

Such an addition only makes sense if the cost is minimal—perhaps something as simple as swapping `memcpy()` with `memcpy_P()` behind a single `#define`. However, the example below highlights another challenge:

```
XXH32_update(state, "ardu", 4);
XXH32_update(state, (PGM_P) F("ino"), 3);
```

Here, `XXH32_update()` must handle both standard pointers and flash-specific pointers within the same session. Simply modifying `libxxhash` for flash access would not be enough, because normal memory access must still function. Designing an interface to accommodate both cases now becomes non-trivial.
At which point, the cost / benefit ratio does no longer look favorable.

**Comment by atesin** [comment] 2024-12-27 18:51
i updated my previous comment to add more info

if you pass the second example to function `XXH32_update(state, string, length)` it will fail because 2nd parameter expect a char* type and receives a PGM_P type instead... although internal working is platform dependent, all platforms i know uses the same macro definition

so if PGM_P is defined, function definition could be simply overloaded and program will choose the appropiate one at runtime, that is PGM_P macro was created for

for better explanations take a look at [arduino](https://docs.arduino.cc/language-reference/en/variables/utilities/PROGMEM), [memory guide](https://docs.arduino.cc/learn/programming/memory-guide/), [esp8266](https://arduino-esp8266.readthedocs.io/en/3.1.2/PROGMEM.html) and [avr](https://avrdudes.github.io/avr-libc/avr-libc-user-manual/group__avr__pgmspace.html) progmem pages

**Comment by Cyan4973** [comment] 2024-12-29 21:15
Separating `XXH32_update()` into two variants—one for standard memory addresses and another for `PGM_P`—is technically feasible but comes with a significant complexity cost to the existing code structure.

In C++, this might appear simpler, as `XXH32_update()` could remain a single named function, routing to specialized implementations based on input type. However, this is misleading; name mangling would still result in two distinct symbols. Library users would then depend on the compiler's name-mangling specifics, which is unacceptable for maintaining compatibility.

In C11, this could be achieved using `_Generic`, allowing `XXH32_update()` to be redefined as a macro that selects the appropriate symbol at compile time. However, in C90, there is no equivalent mechanism. It will require explicitly introducing new entry points, exposing them as part of the public API.

In all cases, the required changes are nontrivial. This is far from being a "simple trick" that is easy to review or maintain. Instead, it involves a complex implementation with additional API entry points and intermediate layers, resulting in significant overhead. The added complexity would burden the API, increase maintenance requirements, and potentially slow down future development.

Given these considerations, unless the implementation complexity can be proven otherwise, I believe this functionality is better handled as an additional layer that copies data from `PGM_P` into standard memory before invoking `XXH32_update()`. Alternatively, a dedicated fork with specialized entry points for direct `PGM_P` access could serve the target purpose more effectively.

**Closed as completed** 2024-12-30 15:54 UTC
